apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iei2umsra-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iei2umsra-go 
  name: iei2umsra-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iei2umsra-go 
